services:

  ventilator:
    build: ./ventilator
    ports:
      - "5050:5050"

  nuner:
    build: ./nuner
    depends_on:
      - minio
      - redis
      - neo4j
    environment:
      MINIO_ENDPOINT: http://minio:9000
      MINIO_ACCESS_KEY: miniouser
      MINIO_SECRET_KEY: miniosecret
      REDIS_URL: redis://redis:6379/0
    ports:
      - "5051:5051"
    volumes:
      - /Users/theapemachine/.cache/huggingface:/home/appuser/.cache/huggingface

  # knowitall:
  #   build: ./knowitall
  #   depends_on:
  #     - minio
  #     - redis
  #     - neo4j
  #   environment:
  #     MINIO_ENDPOINT: http://minio:9000
  #     MINIO_ACCESS_KEY: miniouser
  #     MINIO_SECRET_KEY: miniosecret
  #     REDIS_URL: redis://redis:6379/0
  #   ports:
  #     - "5052:5052"
  #   extra_hosts:
  #     - "host.docker.internal:host-gateway"
  #   volumes:
  #     - /home/theapemachine/.cache/huggingface:/home/appuser/.cache/huggingface

  domainator:
    build: ./domainator
    depends_on:
      - redis
    environment:
      MINIO_ENDPOINT: http://minio:9000
      MINIO_ACCESS_KEY: miniouser
      MINIO_SECRET_KEY: miniosecret
      REDIS_URL: redis://redis:6379/0
    ports:
      - "5053:5053"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - /Users/theapemachine/.cache/huggingface:/home/appuser/.cache/huggingface

  nuner_worker:
    build: ./nuner
    depends_on:
      - redis
    environment:
      MINIO_ENDPOINT: http://minio:9000
      MINIO_ACCESS_KEY: miniouser
      MINIO_SECRET_KEY: miniosecret
      REDIS_URL: redis://redis:6379/0
    command: ["python3", "worker.py"]
    volumes:
      - /Users/theapemachine/.cache/huggingface:/home/appuser/.cache/huggingface
      - ./nuner:/app

  domainator_worker:
    build: ./domainator
    depends_on:
      - redis
    environment:
      MINIO_ENDPOINT: http://minio:9000
      MINIO_ACCESS_KEY: miniouser
      MINIO_SECRET_KEY: miniosecret
      REDIS_URL: redis://redis:6379/0
    command: ["python3", "worker.py"]
    volumes:
      - /Users/theapemachine/.cache/huggingface:/home/appuser/.cache/huggingface

  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      MINIO_ROOT_USER: miniouser
      MINIO_ROOT_PASSWORD: miniosecret
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data

  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"

  neo4j:
    image: neo4j:latest
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/securepassword
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_import_file_use__neo4j__config=true
      - NEO4J_PLUGINS=["apoc"]
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
      - /Users/theapemachine/data:/var/lib/neo4j/import
      - neo4j_plugins:/plugins

  # foucault:
  #   build: ./foucault
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - ./foucault/entrypoints:/app/entrypoints
  #     - ./foucault/.output:/app/.output

  # janusgraph:
  #   image: janusgraph/janusgraph:latest
  #   ports:
  #     - "8182:8182"
  #   environment:
  #     - JANUS_PROPS_TEMPLATE=cql
  #     - janusgraph.storage.backend=cql
  #     - janusgraph.storage.hostname=cassandra
  #   depends_on:
  #     - cassandra
  #
  # cassandra:
  #   image: cassandra:latest
  #   ports:
  #     - "9042:9042"
  #   volumes:
  #     - cassandra_data:/var/lib/cassandra
  #
  # arangodb:
  #   image: arangodb:latest
  #   environment:
  #     ARANGO_ROOT_PASSWORD: yourpassword
  #   ports:
  #     - "8529:8529"
  #   volumes:
  #     - arangodb_data:/var/lib/arangodb3
  #     - arangodb_apps_data:/var/lib/arangodb3-apps

volumes:
  minio_data:
  # arangodb_data:
  # arangodb_apps_data:
  # cassandra_data:
  neo4j_data:
  neo4j_logs:
  neo4j_import:
  neo4j_plugins:
